name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo bash build.sh
          
      - name: Get current date
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "UploadAt-${{ steps.get_date.outputs.date }}"
          name: "Download necessary files"
          body: 'Download ${{ steps.extract_filenames.outputs.filenames }}'
          artifacts: output/*
 
