name: CI

on:
  push:
    branches: [ master ]
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo bash build.sh
          
      - name: Get current date
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "UploadAt-${{ steps.get_date.outputs.date }}"
          name: "Automatic Upload"
          body: 'Upload Images \n Username: live \n Password: live'
          artifacts: /output/*
 
